### ISSUE TITLE
image: /local/planes/casa_noche.jpg missing

### ISSUE THREAD

**Issue by XcOM987** [sergiocasero/sweet_home_3d_ha_lightning#3]
I have an issue where the card isn't displaying correctly and it appears to have not generated the file below

image: /local/planes/casa_noche.jpg

Can I generate this myself or if this is supposed to be generated by the plugin how can I help identify the issue?

![image](https://user-images.githubusercontent.com/47461886/198412473-43a4ae61-4b9a-47d4-9f7e-976e35003eeb.png)

**Comment by XcOM987** [comment]
N/B I've just exported an image myself from the app and it's fixed the layout issue

**Comment by Misiu** [comment]
if the problem is fixed please close the issue

**Comment by XcOM987** [comment]
I would consider it a workarund rather than a fix, I will close the issue as I've solved my own problem, might be worth adding a N/B on the instructions advising to render an image in the same layout and resolution
