### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by guimatheus92** [sergiocasero/sweet_home_3d_ha_lightning#9]
Hi! I hope you guys still are supporting this project.

I really don't know how to activate this plugin, I have created a **plugin** folder in the Sweet Home path, restarted the software but still no clue. Can you guys help please?

My current path is: `C:\Program Files (x86)\Sweet Home 3D\plugins`

**Comment by sergiocasero** [comment]
Honestly I don't know how plugins are installed on windows :(

**Comment by guimatheus92** [comment]
> Honestly I don't know how plugins are installed on windows :(

I gave it a try today again and I was finally able to do it. Here is a guide:

To use it, copy this archive in the plug-ins folder of Sweet Home 3D, which depends on your system as follows:
- under Windows, this folder is C:\Documents and Settings\user\Application Data\eTeks\Sweet Home 3D\plugins,
- under Mac OS X, it's the subfolder Library/Application Support/eTeks/Sweet Home 3D/plugins of your user folder,
- under Linux and other Unix, it's the subfolder .eteks/sweethome3d/plugins of your user folder.
